export default [
  {
    id: 0,
    img: "clip.png",
    name: "Carinber Set",
    price: 12,
    isLimited: false,
    liked: true,
    rating: 4,
  },
  {
    id: 1,
    img: "jaq bag.png ",
    name: "Jaq Bag",
    price: 32,
    isLimited: false,
    liked: false,
    rating: 5,
  },
  {
    id: 2,
    img: "nike-shoe.png",
    name: "Nike Shoe",
    price: 89,
    isLimited: true,
    liked: false,
    rating: 3,
  },
  {
    id: 3,
    img: "",
    name: "Ponca Thermos",
    price: 13,
    isLimited: false,
    liked: false,
    rating: 5,
  },
  {
    id: 4,
    img: "",
    name: "Kamenko Liner",
    price: 120,
    isLimited: false,
    liked: false,
    rating: 2,
  },
  {
    id: 5,
    img: "",
    name: "P.S Cap",
    price: 49,
    isLimited: true,
    liked: true,
    rating: 4,
  },
  {
    id: 6,
    img: "",
    name: "Carinber Set",
    price: 139,
    isLimited: false,
    liked: false,
    rating: 4,
  },
  {
    id: 7,
    img: "",
    name: "Beanie",
    price: 29,
    isLimited: false,
    liked: false,
    rating: 3,
  },
];
